version: '3.8'

services:

    teste-lumi-frontend:
        build:
            context: ./teste-lumi-front
            dockerfile: Dockerfile
        image: teste-lumi-frontend
        ports:
            - 3000:3000
        volumes:
            - './teste-lumi-front:/app'
            - '/app/node_modules'
        environment:
            NODE_ENV: development
            REACT_APP_API_ADDRESS: http://localhost:8000
        stdin_open: true
        tty: true
    teste-lumi-backend:
            build:
                context: ./testeLumiBack
                dockerfile: Dockerfile
            image: teste-lumi-backend
            ports:
                - 8000:8000
            volumes:
                - './testeLumiBack:/app'
                - '/app/node_modules'
            environment:
                NODE_ENV: development
                PORT: 8000
                DB_HOST: teste-lumi-db
                DB_USER: root
                DB_PASS: root
                DB_NAME: teste-lumi-db
            depends_on:
                - teste-lumi-db
    teste-lumi-db:
        image: postgres:latest
        container_name: postgres_db
        environment:
          POSTGRES_DB: teste-lumi-db
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: