name: Deploy Back-end to Heroku

on:
  push:
    branches:
      -main

jobs:

  build: 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
  
  steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: npm install --silent

    - name: Run tests
      uses: npm run test